### ISSUE TITLE
2. Station

### ISSUE THREAD

**Issue by btro1404** [skuethe/MMM-HH-LocalTransport#1]
Zwei Haltestellen anzuzeigen, scheint nicht möglich zu sein. Wenn das Modul ein zweites mal (mit einer anderen Stations-ID) eingebunden wird, wird die zuerst definierte Haltestelle auch unter dem zweiten header angezeigt.

**Comment by skuethe** [comment]
Das ist richtig. Die config wird dem `node_helper.js` übergeben. Node helper unterstützt von MM² Wegen her keine multi Instanzen. Man müsste das Modul also umbauen, damit die station ID von der jeweiligen Instanz des `MMM-HH-LocalTransport.js` in den API request übernommen wird.

**Comment by btro1404** [comment]
Hört sich nicht trivial an. 
Gäbe es auch die Möglichkeit zB MMM-HH-LocalTransport-a.js und MMM-HH-LocalTransport-b.js zu integrieren und diese dann in der config zu definieren? Oder müssten es ganze (funktionell identische) Module sein, die man komplett zusätzlich installiert?

**Comment by skuethe** [comment]
Das Zweite. Wobei ich das noch nicht getestet habe.
Vorgehen wäre also (in der Theorie):

- `MMM-HH-LocalTransport` Ordner kopieren: `MMM-HH-LocalTransport2`
- Dateien umbenennen
  - `MMM-HH-LocalTransport2\MMM-HH-LocalTransport.css` in `MMM-HH-LocalTransport2\MMM-HH-LocalTransport2.css`
  -  `MMM-HH-LocalTransport2\MMM-HH-LocalTransport.js` in `MMM-HH-LocalTransport2\MMM-HH-LocalTransport2.js`
- `MMM-HH-LocalTransport2\MMM-HH-LocalTransport2.js` editieren:
  - Zeile 11: `Module.register("MMM-HH-LocalTransport2",{`
  - Zeile 36; `return ["MMM-HH-LocalTransport2.css", "font-awesome.css"];`

**Comment by btro1404** [comment]
Jo, klappt!

Zusätzlich habe ich, anstatt das Verzeichnis `node_modules` zu kopieren, einen Symlink `MMM-HH-LocalTransport2/node_modules` angelegt, der auf `../MMM-HH-LocalTransport/node_modules` verweist. Damit spare ich mir neben ein bisschen Speicherplatz wahrscheinlich auch etwas Aufwand, wenn du mal eine neue Version veröffentlichst.

Vielen Dank!
