### ISSUE TITLE
Canot read properties of undefinded

### ISSUE THREAD

**Issue by b-reich** [skuethe/MMM-HH-LocalTransport#11]
Hi, ich versuche gerade Plugin bei mir einzurichten.

Dabei bin ich  auf den folgenden Fehler gestoßen:

```
[05.04.2022 11:51.18.181] [ERROR] Whoops! There was an uncaught exception...
[05.04.2022 11:51.18.190] [ERROR] TypeError: Cannot read properties of undefined (reading 'time')
    at Class.processTrains (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_helper.js:114:30)
    at /home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_helper.js:100:30
    at Request.handleRequestResponse [as _callback] (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/unirest/index.js:552:70)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
```
Das ganze resultiert in:
![image](https://user-images.githubusercontent.com/1573025/161733389-75f5e6cb-3f63-41f2-bc3b-ca9e9c518290.png)

**Comment by skuethe** [comment]
Das exception handling ist dort sicherlich verbesserungswürdig, aber ich würde mal auf einen fehlerhaften return von der API tippen.
https://gti.geofox.de/v3/api-docs/public
-> der `DLResponse` hat ein required attribute `time`.

Bitte login an die geofox API validieren.

**Comment by b-reich** [comment]
Mhmm Login sollte passen
![grafik](https://user-images.githubusercontent.com/1573025/161833196-93b4e8a9-2117-4621-97eb-86bfa3aa456e.png)
```
            module: 'MMM-HH-LocalTransport',
            position: 'top_left',
            header: 'HVV - Connections',
            config: {
                id: 'Master:9910910', // Trainstation ID
                apiKey: 'P6gxxxxxxx', // Add your apiKey
                apiUser: 'BenjaminReich', // Add your apiUser
                maximumEntries: '5' // Max departures displayed
            }
```

**Comment by b-reich** [comment]
Ich habe ein "=" im Password/ApiKey vielleicht ist das ein Problem?
Ansonsten, installiert via mmpm.

**Comment by b-reich** [comment]
@skuethe hast du noch eine Idee?

**Comment by skuethe** [comment]
Schau doch mal was der return von der API genau ist, z.B. via
https://github.com/skuethe/MMM-HH-LocalTransport/blob/3e460236917d2d14e088cde55cdd2b3a1eb87c94/node_helper.js#L99

**Comment by b-reich** [comment]
> Schau doch mal was der return von der API genau ist, z.B. via
> 
> https://github.com/skuethe/MMM-HH-LocalTransport/blob/3e460236917d2d14e088cde55cdd2b3a1eb87c94/node_helper.js#L99

Sorry, ich bin jetzt erst wieder dazu gekommen.

```
[INFO]  body:  {"returnCode":"ERROR_TEXT","errorDevInfo":"0 Please provide a station object with a valid id, e.g. by running a CNRequest first. Station [Haltestelle: (0;null;;;;Master:9910910)] could not be resolved!"}
```

Meine aktuelle Config:
```
        {
            module: 'MMM-HH-LocalTransport',
            position: 'top_left',
            header: 'HVV - Connections',
            config: {
                //id: '9910910', // Trainstation ID
                id: 'Master:9910910',
                apiKey: 'P6*****',
                apiUser: 'Be*****',
                maximumEntries: '5' // Max departures displayed
            }
         }
```

**Comment by skuethe** [comment]
"Please provide a station object with a valid id"

**Comment by b-reich** [comment]
Ok, es ist nicht hilfreich wenn der default eine falsche ID hat. Hab den default genommen gehabt.
https://github.com/skuethe/MMM-HH-LocalTransport/blob/3e460236917d2d14e088cde55cdd2b3a1eb87c94/MMM-HH-LocalTransport.js#L30

~Angezeigt bekomme ich leider trotzdem nichts.~

Jetzt gehts, Danke!
