### ISSUE TITLE
Erstellung API-Key & API-User?

### ISSUE THREAD

**Issue by xIExodusIx** [skuethe/MMM-HH-LocalTransport#12]
Hallo Skuethe,

auch dies ist nicht wirklich ein Issue, aber wie erstelle ich für dieses Modul den benötigten API-Key und API-User? Habe diese beim HVV vor 2 Wochen beantragt und heute per Mail etwas erhalten das weder einen API-Key noch einen API-User enthielt. Nur dieses:

Benutzername für die Authentifizierung: "Mein Benutzer" --> aus Sicherheitsgründen entfernt!  
Passwort für die Signatur-Erzeugung zur Authentifizierung: "Kryptische Zeichenfolge" --> aus Sicherheitsgründen entfernt!
Der DNS-Name des Servers ist: gti.geofox.de

Sowie einen Link zu einem Handbuch!

Damit komme ich nicht weiter, da ich nicht weiss wo und wie ich diese verwenden muss. Das Handbuch ist wenig Hilfreich, da dort nur beschrieben wird wie man was programmieren mus, da ich aber des Programmierens nicht fähig bin verstehe ich nur Bahnhof. Nun stehe ich hier und schaue wie die Kuh wenns donnert. 

Warum müssen manche Institutionen alles nur so unendlich kompliziert machen? Wo anders bekommme ich einen API-Key auf der Web-Site per Mausklick!
Einfach, bequem und elegant geht auf jedenfall anders!

Gruß  xIExodusIx

**Comment by xIExodusIx** [comment]
Habs hinbekommmen,  funktioniert über die "findstation.js" man sollte allerdings hier die Hochkamma ( ` ` ) gegen Anführungszeichen ( " " ) austauschen, am besten auch im Modul, eigentlich überall, dann funktionierts auch.

findstation.js "Passwort" "Benutzername" "Station"

und man erhält: 

sig:  kryptische Zeichenfolge   --> dies ist der API-Key!
ID:    Master:xxxxxxx                 --> Dies ist  die Stations ID!

Puhh schwere Geburt ;-)

**Comment by xIExodusIx** [comment]
Aber nun bekomme ich einen "Connection Error" bzw. "Fehler beim Verbindungsaufbau"  auf dem Spiegel angezeigt anstatt der Verbindungen!
Wo ist denn nun schon wieder der Fehler?

**Comment by skuethe** [comment]
Moinsen,

wo nun der Fehler genau liegt ist ohne weitere Daten schwer zu sagen.
Bitte nochmal verifizieren ob alle Schritte aus der Installationsanleitung durchgeführt wurden:
https://github.com/skuethe/MMM-HH-LocalTransport#install

Danach würde die Logausgabe vom magicmirror sonst weiterhelfen.

**Comment by xIExodusIx** [comment]
> Moinsen,
> 
> wo nun der Fehler genau liegt ist ohne weitere Daten schwer zu sagen. Bitte nochmal verifizieren ob alle Schritte aus der Installationsanleitung durchgeführt wurden: https://github.com/skuethe/MMM-HH-LocalTransport#install
> 
> Danach würde die Logausgabe vom magicmirror sonst weiterhelfen.

im pm2 log steht: MMM-HH-LocalTransport : Error: got 401 response
Ich denke dass weist auf eine fehlerhafte Authentifizierung hin.
Und noch dieser:  MMM-HH-LocalTransport : body:  {"returnCode":"ERROR_TEXT","errorText":"A technical problem occured while processing your request.","errorDevInfo":"Authentication failed!"}

**Comment by xIExodusIx** [comment]
Auch dieses Problem ist gelöst!
Wie bei "findstation.js" wird das kryptische Authentifizierungs-Passwort aus der Mail vom HBT Hamburger Berater Team GmbH als API-Key eingesetzt.

**Comment by skuethe** [comment]
Dann viel Spass damit. Ich schließe das Issue mal.
