### ISSUE TITLE
Änderungswunsch [kein Issue]

### ISSUE THREAD

**Issue by xIExodusIx** [skuethe/MMM-HH-LocalTransport#13]
Hallo Skythe,
ich würde gerne die  Tabelle umstellen, und zwar in der Form "Line (Icon), Ziel (Richtung), Abfahrt in, +Verspätung". 
Ich habe auch schon versucht das in der "MMM-HH-LocalTransport.css" umzustellen, leider ohne Erfolg. 

Wo und wie kann ich das Aussehen der Tabelle ändern? Es würde mir etwas Platz auf dem Spiegel bringen und nicht bei  langen Zielen (z.B. "7 min +2 29 Bf. Bergedorf (Johann-Meyer-Straße") in andere Modul-Anzeigen reinreichen, wenn ich das so umstellen und linksbündig ausrichten könnte.  Also so: "29 Bf. Bergedorf (Johann-Meyer-Straße) 7min +2" Das würde auch der elektronischen Anzeige an Busbahnhöfen näher kommen.

Danke für die Unterstützung.

**Comment by xIExodusIx** [comment]
Hallo Skythe,

habs heraussgefunden und hinbekom. 
Dieser Issue kann geschlossen werden.

**Comment by skuethe** [comment]
👍🏽
