### ISSUE TITLE
komme über "loading connections" nicht hinaus

### ISSUE THREAD

**Issue by partyblitzer** [skuethe/MMM-HH-LocalTransport#3]
Hi skuehte, 

vielen Dank, dass du das Modul auf den neuen Stand gebracht hast. Bei mir funktioniert es leider trotzdem nicht, wie schon das Vorgängermodul.... Es liegt höchst wahrscheinlich daran, dass  ich nur sehr sehr wenig Ahnung habe, wie so viele hier. 
ABER:
immerhin konnte ich schon die StationsID und den Token generieren.... (das klappte bisher nicht)

APIkey und APIuser muss ich - wie angeben - in der config eingeben, da wird ja auch die StadionsID eingetragen und der Token gehört in die "MMM-HH-LocalTransport.js", oder? 

dann erscheint bei mir nur, dass Verbindungen geladen werden....

auch wenn ich in der "MMM-HH-LocalTransport.js" key und user eintrage, passiert nicht mehr. 

Was mache ich falsch? Bin dankbar für Hilfe und stelle auch gerne "Spenden" bei https://ko-fi.com/ oder auf anderen Plattformen bereit...

Beste Grüße Partyblitzer

**Comment by skuethe** [comment]
Moin,

das Modul benötigt generell mal etwas Überarbeitung, ich habe aktuell jedoch leider kaum Zeit.
Vom Fehler her: du benötigst nur die StationsID (z.B. `Master:9910910` = HBF) sowie den apiKey und den apiUser (vom HVV / Geofox). Einen Token musst du nirgendwo eintragen. Generell musst Du nichts an der `MMM-HH-LocalTransport.js` verändern.

Also nochmal zusammengefasst: nur die StationsID (welche bei [Schritt nr. 3](https://github.com/skuethe/MMM-HH-LocalTransport#install) ausgegeben wird) sowie den apiKey und den apiUser (welche Dir vom HVV / Geofox mitgeteilt werden) müssen in der MM² config hinterlegt werden.

Prüfe das doch nochmal, dann schauen wir ob wir das Problem auf die Schnelle schon behoben bekommen.

Gruß

**Comment by partyblitzer** [comment]
Wow, vielen Dank. Es hat geklappt. Aber ;-) gibt es eine Möglichkeiten Busse auszublenden oder nur die Abfahrten anzuzeigen, die nicht jetzt, sondern erst in fünf Minuten, quasi Wegzeit... 
Besten Dank!!

**Comment by skuethe** [comment]
Es gibt laut [Geofox API Dokumentation wohl die Möglichkeit zu filtern](https://gti.geofox.de/html/GTIHandbuch_p.html#x1-470002.4.3) (also z.B. nur Busse, nur Ubahn, etc.). Das ist in dem Modul aber (noch) nicht umgesetzt.

Die Wegzeit lässt sich aktuell leider auch (noch) nicht beeinflussen. Aktuell wird immer fest die aktuelle Uhrzeit als Abfahrtszeit angegeben. Hier müsste eine neue Konfigurationsoption hinzugefügt werden damit man einen "offset" definieren kann.

**Comment by partyblitzer** [comment]
Besten Dank nochmals, auch für die Aktualisierung des Moduls... 
habe da in einem anderen Modul aus [Berlin](https://github.com/deg0nz/MMM-PublicTransportBerlin) genau diese beiden Punkte gefunden. Ich denke zwar, dass ich es nicht schaffe sie einzubinden, aber werden es probieren...
